services:
  helloflask:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: helloflask:1.0.0
    container_name: HelloFlask
    network_mode: bridge
    ports:
      - "8080:8080"
    environment:
      HOST: "host.docker.internal"
      USER: "hello"
      PASSWORD: "h"
      DATABASE: "hello"
    extra_hosts:
      - "host.docker.internal:host-gateway"
